### ISSUE TITLE
Compiling problems using cmake

### ISSUE THREAD

**Issue by XiaoboLinlin** [srtee/lammps-USER-CONP2#10]
Hi Shern,

I am trying to compile the lammps with your added function, but the program produced error like this. 

```
Undefined symbols for architecture x86_64:
  "_ddot_", referenced from:
      LAMMPS_NS::FixConp::get_setq() in liblammps.a(fix_conp.cpp.o)
      LAMMPS_NS::FixConp::update_charge() in liblammps.a(fix_conp.cpp.o)
  "_dgetrf_", referenced from:
      LAMMPS_NS::FixConp::inv() in liblammps.a(fix_conp.cpp.o)
  "_dgetri_", referenced from:
      LAMMPS_NS::FixConp::inv() in liblammps.a(fix_conp.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lmp] Error 1
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
make: *** [all] Error 2
```

Any suggestions for solving this problem?

The command line I used is this: 
```
cd lammps
mkdir build
cd build
cmake ../cmake           # configuration reading CMake scripts from ../cmake
cmake --build .          # compilation (or type "make")

```

**Comment by srtee** [comment]
Thank you for your interest! These are standard BLAS and LAPACK functions, so the error message means that your compiler was not able to link to BLAS and LAPACK headers.

Can you tell me a bit more about the BLAS and LAPACK installation on your system?

**Comment by srtee** [comment]
If you have not yet installed a LAPACK library, try using this script: https://github.com/eddelbuettel/mkl4deb/blob/master/script.sh to get Intel MKL 2018 as a nice apt-get package, then try compiling again.

**Comment by XiaoboLinlin** [comment]
Hi Shern,

Thank you so much for your help!. I tried to install LAPACK to my lammps source code using the script link you sent me, but did not work. This is probably because I am using mac system but your script is for linux. Alternatively, I found the github website for lapack (https://github.com/Reference-LAPACK/lapack). Is this the LAPACK library you mentioned? I git cloned the repo in lammps/src/ directory, and compiled the lapack package first and then tried to compile the lammps, but still failed. I also tried conda install -c conda-forge lapack, but it also did not work. I am not very familiar with C++. If you can let me know the detailed install procedures for lapack/blas, that will be really helpful. 

Best,

Xiaobo



> If you have not yet installed a LAPACK library, try using this script: https://github.com/eddelbuettel/mkl4deb/blob/master/script.sh to get Intel MKL 2018 as a nice apt-get package, then try compiling again.

**Comment by srtee** [comment]
Hi Xiaobo,

Unfortunately I don't work on Mac systems (so it will be valuable for you to test my code!)

You can install the Mac version of Intel MKL here: https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html?operatingsystem=mac&distributions=webdownload&options=offline 

Then run the appropriate setvars script:
for sudo / root installation: . opt/intel/oneapi/setvars.sh
for local / user installation: . ~/intel/oneapi/setvars.sh

and try to recompile! Let me know how it goes!

**Comment by XiaoboLinlin** [comment]
Hi Shern,

I finally got the .a files (`librefblas.a`   and` liblapack.a` ), I think they are the libs we want, but I am stuck on here. How do you link the two libs to lammps before compile lammps?

Best,

Xiaobo

**Comment by XiaoboLinlin** [comment]
> Hi Xiaobo,
> 
> Unfortunately I don't work on Mac systems (so it will be valuable for you to test my code!)
> 
> You can install the Mac version of Intel MKL here: https://software.intel.com/content/www/us/en/develop/tools/oneapi/base-toolkit/download.html?operatingsystem=mac&distributions=webdownload&options=offline
> 
> Then run the appropriate setvars script:
> for sudo / root installation: . opt/intel/oneapi/setvars.sh
> for local / user installation: . ~/intel/oneapi/setvars.sh
> 
> and try to recompile! Let me know how it goes!

Hi Shern,

Just tried your Mac MKL way. When I run `. opt/intel/oneapi/setvars.sh` in my root, it produced results:
```
:: initializing oneAPI environment ...
   BASH version = 3.2.57(1)-release
:: tbb -- latest
:: mkl -- latest
:: dev-utilities -- latest
:: oneAPI environment initialized ::
```
And then recompile lammps using cmake. The compiling produced the same error as before. 
Any suggestions for that?

best,

Xiaobo

**Comment by srtee** [comment]
Then cmake still cannot find the MKL files. Try setting the include and library folders directly with the following flags:

-D FFT=MKL (actually maybe just this flag could work -- let me know if it does)
-D MKL_INCLUDE_DIR= ...
-D MKL_LIBRARY= ...

where the folders will depend on your system setup.

**Comment by XiaoboLinlin** [comment]
> Then cmake still cannot find the MKL files. Try setting the include and library folders directly with the following flags:
> 
> -D FFT=MKL (actually maybe just this flag could work -- let me know if it does)
> -D MKL_INCLUDE_DIR= ...
> -D MKL_LIBRARY= ...
> 
> where the folders will depend on your system setup.

Hi Shern,

I am not sure what you mean for `Try setting the include and library folders directly with the following flags`, because I am not very familiar with C++.  Do mean type `cmake -D FFT=MKL` in the directory of `/opt/intel/oneapi` ?

**Comment by srtee** [comment]
Hi Xiaobo,

This means calling the `cmake` command with additional flags, for example, instead of just `cmake ../cmake` you would call:

```
cmake -D FFT=MKL ../cmake
```

See the LAMMPS website for many more cmake flags that might be important for you: https://lammps.sandia.gov/doc/Howto_cmake.html

Hope that helps!

**Comment by XiaoboLinlin** [comment]
> Hi Xiaobo,
> 
> This means calling the `cmake` command with additional flags, for example, instead of just `cmake ../cmake` you would call:
> 
> ```
> cmake -D FFT=MKL ../cmake
> ```
> 
> See the LAMMPS website for many more cmake flags that might be important for you: https://lammps.sandia.gov/doc/Howto_cmake.html
> 
> Hope that helps!

Thank you so much for detailed explanation, but it still produced the same errors as before. 
I used command line of `cmake -D FFT=MKL ../cmake`  and `cmake --build .` in `lammps/build/` directory.

**Comment by XiaoboLinlin** [comment]
Hi Shern,

I added the line` #include <Accelerate/Accelerate.h>` to fix_conp.cpp file according to this website (https://stackoverflow.com/questions/10112135/understanding-lapack-calls-in-c-with-a-simple-example), it looks it sort of started to work, but still have errors, looks like the accelerated framework can not be overloaded. Compiling errors are shown below:
```
In file included from /Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:25:
In file included from /Users/xiaobolin/install_software/lammps/src/atom.h:17:
/Users/xiaobolin/install_software/lammps/src/pointers.h:39:9: warning: 'MIN' macro redefined
      [-Wmacro-redefined]
#define MIN(A,B) ((A) < (B) ? (A) : (B))
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/param.h:215:9: note: previous
      definition is here
#define MIN(a, b) (((a)<(b))?(a):(b))
        ^
In file included from /Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:25:
In file included from /Users/xiaobolin/install_software/lammps/src/atom.h:17:
/Users/xiaobolin/install_software/lammps/src/pointers.h:40:9: warning: 'MAX' macro redefined
      [-Wmacro-redefined]
#define MAX(A,B) ((A) > (B) ? (A) : (B))
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/param.h:218:9: note: previous
      definition is here
#define MAX(a, b) (((a)>(b))?(a):(b))
        ^
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:69:8: error: functions that differ only in
      their return type cannot be overloaded
  void dgetrf_(const int *M,const int *N,double *A,const int *lda,int *ipiv,int *info);
  ~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:2768:5: note: 
      previous declaration is here
int dgetrf_(__CLPK_integer *__m, __CLPK_integer *__n, __CLPK_doublereal *__a,
~~~ ^
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:70:8: error: functions that differ only in
      their return type cannot be overloaded
  void dgetri_(const int *N,double *A,const int *lda,const int *ipiv,double *work,const int *lwor...
  ~~~~ ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers/clapack.h:2773:5: note: 
      previous declaration is here
int dgetri_(__CLPK_integer *__n, __CLPK_doublereal *__a, __CLPK_integer *__lda,
~~~ ^
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:1582:1: warning: '/*' within block comment
      [-Wcomment]
/*
^
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:1583:1: warning: '/*' within block comment
      [-Wcomment]
/* ---------------------------------------------------------------------- */
^
4 warnings and 2 errors generated.
CMakeFiles/lammps.dir/build.make:1752: recipe for target 'CMakeFiles/lammps.dir/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp.o' failed
make[2]: *** [CMakeFiles/lammps.dir/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/lammps.dir/all' failed
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
Any suggestions for that?

**Comment by srtee** [comment]
Hi Xiaobo,

You shouldn't have to add any different header files. Try recompiling using the following:

```
cmake -D FFT=MKL \
-D MKL_INCLUDE_DIR=opt/intel/oneapi/mkl/include \
-D MKL_LIBRARY=opt/intel/oneapi/mkl/lib/intel64 \
../cmake
```

and let me know how it goes. If it compiles but does not run you may have a problem linking the MKL library at runtime and you may have to do this:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:opt/intel/oneapi/mkl/lib/intel64
```

and subsequently add that line to your .zshrc or equivalent profile setup.

**Comment by srtee** [comment]
Alternatively try

```
cmake -D CMAKE_CXX_FLAGS='-lblas -llapack'../cmake
```

and see if that gets the compiler to link to whatever default BLAS/LAPACK installation already exists on your system.

**Comment by XiaoboLinlin** [comment]
Hi Shern,

I tried both of your ways, but they are not working (the same errors). The command line I used is 
`cmake -D FFT=MKL -D MKL_INCLUDE_DIR=/opt/intel/oneapi/mkl/2021.1.1/include -D MKL_LIBRARY=/opt/intel/oneapi/mkl/2021.1.1/lib ../cmake`  

Btw, your alternative way also produced warnings (similar to previous errors). The results are below:
```
[ 38%] Building CXX object CMakeFiles/lammps.dir/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp.o
clang: warning: -lblas: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -llapack: 'linker' input unused [-Wunused-command-line-argument]
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:1583:1: warning: '/*' within block comment [-Wcomment]
/*
^
/Users/xiaobolin/install_software/lammps/src/fix_conp.cpp:1584:1: warning: '/*' within block comment [-Wcomment]
/* ---------------------------------------------------------------------- */
^
2 warnings generated.
[ 38%] Building CXX object CMakeFiles/lammps.dir/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp.o
clang: warning: -lblas: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -llapack: 'linker' input unused [-Wunused-command-line-argument]
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp:116:100: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
            if (me == 0) fprintf(outf,"At step %d, couldn't increase or decrease check interval\n",update->ntimestep);
                                               ~~                                                  ^~~~~~~~~~~~~~~~~
                                               %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp:120:108: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
  ...if (me == 0) fprintf(outf,"At step %d, increasing explicit check interval to every %d steps\n",update->ntimestep,dyn_inte...
                                        ~~                                                          ^~~~~~~~~~~~~~~~~
                                        %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp:124:108: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
  ...if (me == 0) fprintf(outf,"At step %d, decreasing explicit check interval to every %d steps\n",update->ntimestep,dyn_inte...
                                        ~~                                                          ^~~~~~~~~~~~~~~~~
                                        %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp:127:93: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
            if (me == 0) fprintf(outf,"At step %d, initializing dynamic update, stage %d\n",update->ntimestep,dyn_status);
                                               ~~                                           ^~~~~~~~~~~~~~~~~
                                               %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn.cpp:196:1: warning: control may reach end of non-void function
      [-Wreturn-type]
}
^
5 warnings generated.
[ 38%] Building CXX object CMakeFiles/lammps.dir/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn2.cpp.o
clang: warning: -lblas: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -llapack: 'linker' input unused [-Wunused-command-line-argument]
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn2.cpp:137:51: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
          fprintf(outf,"%d\tbk\t%d\t%d\t%g\t%g\n",update->ntimestep,bk_interval,bk_interval_new,bk_err,bk_runerr);
                        ~~                        ^~~~~~~~~~~~~~~~~
                        %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn2.cpp:179:51: warning: format specifies type 'int' but the argument has
      type 'LAMMPS_NS::bigint' (aka 'long long') [-Wformat]
          fprintf(outf,"%d\tbp\t%d\t%d\t%g\t%g\n",update->ntimestep,bp_interval,bp_interval_new,bp_err,bp_runerr);
                        ~~                        ^~~~~~~~~~~~~~~~~
                        %lld
/Users/xiaobolin/install_software/lammps/src/fix_conp_dyn2.cpp:264:1: warning: control may reach end of non-void function
      [-Wreturn-type]
}
^
3 warnings generated.
```


It looks the fix_conp.cpp can not connect to the lib.

Any suggestions for that?

**Comment by srtee** [comment]
Hi Xiaobo,

It looks like it should be able to compile correctly with the second way (the warnings can be ignored). Can you try to complete the compiling with `cmake --build .`?

By the way, this method installs LAMMPS without any add-ons, and so it won't be useful for any simulations. Once the compilation for fix conp is working, you may need to retry using

```
cmake -C ../cmake/presets/minimal.cmake ../cmake
```

to make sure that important packages like MOLECULE and KSPACE are installed.

**Comment by XiaoboLinlin** [comment]
> Hi Xiaobo,
> 
> It looks like it should be able to compile correctly with the second way (the warnings can be ignored). Can you try to complete the compiling with `cmake --build .`?
> 
> By the way, this method installs LAMMPS without any add-ons, and so it won't be useful for any simulations. Once the compilation for fix conp is working, you may need to retry using
> 
> ```
> cmake -C ../cmake/presets/minimal.cmake ../cmake
> ```
> 
> to make sure that important packages like MOLECULE and KSPACE are installed.
> 
> (Also, for the first way, you are probably still missing one sub directory from your MKL library setting. The directory that you supply needs to contain the .so / .dylib files for MKL.)

Hi Shern, 

The warning results I posted are actually the results after I ran `cmake --build .` Is this warning still okay?

I used the sentence (`cmake -C ../cmake/presets/minimal.cmake ../cmake`) to install other packages, but when I check package using `make ps `in `lammps/src` directory, I saw no packaged installed. So I instead used the command line , `make yes-standard`, to install some standard packages including the package you mentioned. Is this process okay?

**Comment by srtee** [comment]
Hi, if there is an executable file in the `build` directory then it should be okay. You can try running it and then run lmp -help to see if the packages have been successfully installed.

**Comment by XiaoboLinlin** [comment]
> Hi, if there is an executable file in the `build` directory then it should be okay. You can try running it and then run lmp -help to see if the packages have been successfully installed.

Hi Shern,

Thank you so much! Looks it is working. I tested your modified lammps using the lmp_test.sh file in your test directory. But the error produced:
like 
```
ERROR: Unrecognized fix style 'conp/v0' (../modify.cpp:900)
ERROR: Unrecognized fix style 'conp/v1' (../modify.cpp:900)
ERROR: Unrecognized fix style 'conp/v2' (../modify.cpp:900)
ERROR: Unrecognized fix style 'conp' (../modify.cpp:900)
```

Any suggestions for that?

**Comment by srtee** [comment]
Hi Xiaobo,

Apologies for the incorrect script left in the test directory (which is meant to be used with the dev branch). You can test the conp fix by running the examples in the tests/dilute directory with the following commands:

`for n in {0..5}; do export N=$n; lmp -i input; done`

But in your previous output fix conp is not recognised, and since there were no compilation errors it suggests that something has gone wrong in linking fix conp to the LAMMPS core code. I have only used this package in LAMMPS compiled purely with cmake, so I have a feeling that mixing in `make yes-standard` leads to a very different outcome (probably because the makefiles from the main LAMMPS repository do not account for custom fixes?).

I can only suggest that you try a clean recompile using only cmake. It will be normal that all built files will be in your build directory and there will be no new files in your `lammps/src` directory (this is the advantage of cmake over make, as the compilation can be cleaned up simply by deleting the build directory). Beyond that, I think you will need help either from the LAMMPS mailing list or from Mac experts you may know.

**Comment by XiaoboLinlin** [comment]
Hi Shern,

It is now working! I realize I used wrong executable file location. And the code is working either on my mac computer and remote supercomputer cluster (NERSC).  Really thank you for helping me out! Much appreciate it!

Additionally, I noticed that previous zhenxingwang' repo says the code has limitation of "The simulation cell must be symmetric with respect to z=0 plane". Does you code also have the similar limitation? since I may want to set the cell symmetric with respect to like y = 90 angstrom.

Best,

Xiaobo

**Comment by srtee** [comment]
> Additionally, I noticed that previous zhenxingwang' repo says the code has limitation of "The simulation cell must be symmetric with respect to z=0 plane". Does you code also have the similar limitation? Since I may want to set the cell symmetric with respect to like y = 90 angstrom, and the periodic boundary is set at all directions (not only x and y, but also x,y,z), and the electrodes will be very thick with pores inside, and the electrode materials may not be only carbons. Do you think your code would work in the system like this?

Hi Xiaobo,

Apologies for replying late -- I have been busy with other things the past few days. I did not directly develop the previous code so I do not know exactly what they observed. But I know that their previous code did not preserve the electroneutrality of the electrode pair, so together with their use of an older form of the dipole term (see Yeh & Hummer 1999 and Ballenegger 2005 -- both citations can be found in the documentation for the old conp / LAMMPS documentation for modify slab), I imagine they had problems with a z-imbalanced cell as well.

I have not tested my code with similar situations (it is usually easy to ensure that the electrodes are cell-centered with a simple translation). If there are additional constraints, the code should still work. If you are planning to do a natively 3D-periodic simulation (that is, you are not trying to approximate a realistically slab-like system), you can try using the _noslab_ flag, but you need to be sure that the mathematics implemented in the LAMMPS + conp code matches up with the physics you are actually trying to simulate. It sounds like you are trying to do some interesting things -- feel free to email me for further help or collaboration.

All the best,
Shern

**Comment by XiaoboLinlin** [comment]
> > Additionally, I noticed that previous zhenxingwang' repo says the code has limitation of "The simulation cell must be symmetric with respect to z=0 plane". Does you code also have the similar limitation? Since I may want to set the cell symmetric with respect to like y = 90 angstrom, and the periodic boundary is set at all directions (not only x and y, but also x,y,z), and the electrodes will be very thick with pores inside, and the electrode materials may not be only carbons. Do you think your code would work in the system like this?
> 
> Hi Xiaobo,
> 
> Apologies for replying late -- I have been busy with other things the past few days. I did not directly develop the previous code so I do not know exactly what they observed. But I know that their previous code did not preserve the electroneutrality of the electrode pair, so together with their use of an older form of the dipole term (see Yeh & Hummer 1999 and Ballenegger 2005 -- both citations can be found in the documentation for the old conp / LAMMPS documentation for modify slab), I imagine they had problems with a z-imbalanced cell as well.
> 
> I have not tested my code with similar situations (it is usually easy to ensure that the electrodes are cell-centered with a simple translation). If there are additional constraints, the code should still work. If you are planning to do a natively 3D-periodic simulation (that is, you are not trying to approximate a realistically slab-like system), you can try using the _noslab_ flag, but you need to be sure that the mathematics implemented in the LAMMPS + conp code matches up with the physics you are actually trying to simulate. It sounds like you are trying to do some interesting things -- feel free to email me for further help or collaboration.
> 
> All the best,
> Shern

No worry, Shern. Thank you so much for your good suggestions and help! I will let you know if any help I may need and potential collaborations.

Best,

Xiaobo Lin
