### ISSUE TITLE
Question on running on cluster

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#12]
Hello,

Could you please let me know whether can we run it on linux clusters?

Best regards

**Comment by srtee** [comment]
Hi, this code is a package for the LAMMPS molecular dynamics simulator (https://github.com/lammps/lammps). It can be compiled together with LAMMPS in any Linux environment -- the admins of your cluster should know what to do.

**Comment by saffari101** [comment]
Hi Dr. Tee,
Thanks a lot for your reply.
