### ISSUE TITLE
Need help for installing CONP2

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#19]
Hi Dear Shern,

First of all, I appreciate you for the contribution for conp2. I confront an error when compiling in ubuntu 18 cloud. Since I'm newbie, I couldn't find out the reason. I list briefly my steps. I do appreciate your help and the time you spend for it. 

**1. Get the last stable release lammps tarball**
**2.  Install LAPACK and BLAS from:** _"https://github.com/eddelbuettel/mkl4deb/blob/master/script.sh"_
**3. Link LAPCK and BLAS:** _"LIB = -lblas -llapack"_
**4. Copy cpp/h files from conp2 into src**
**5.  In buid directory:** _"cmake -D PKG_MOLECULE=yes -D PKG_RIGID=yes -D PKG_KSPACE=yes -D PKG_MANYBODY=yes -D INTEL_ARCH=cpu -D INTEL_LRT_MODE=threads -D PKG_USER-OMP=yes ../cmake"
"_

**Output:**

-- Running check for auto-generated files from make-based build system
-- Checking for module 'fftw3'
--   No package 'fftw3' found
-- Generating style headers...
-- Generating package headers...
-- Generating lmpinstalledpkgs.h...
-- The following tools and libraries have been found and configured:
 * Git
 * OpenMP
 * PkgConfig

-- <<< Build configuration >>>
   Operating System: Linux
   Build type:       RelWithDebInfo
   Install path:     /root/.local
   Generator:        Unix Makefiles using /usr/bin/make
-- Enabled packages: KSPACE;MANYBODY;MOLECULE;RIGID;USER-OMP
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       7.5.0
      C++ Flags:     -O2 -g -DNDEBUG
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=3;LAMMPS_GZIP;FFT_KISS;LMP_USER_OMP
-- C compiler:       /usr/bin/cc
      Type:          GNU
      Version:       7.5.0
      C Flags:       -O2 -g -DNDEBUG
-- <<< Linker flags: >>>
-- Executable name:  lmp
-- Static library flags:
-- <<< FFT settings >>>
-- Primary FFT lib:  KISS
-- Using double precision FFTs
-- Using non-threaded FFTs
-- Configuring done
-- Generating done
-- Build files have been written to: /lammps-29Oct20/build

**6. Compile:** _"cmake --build ."_  

Warnings and Errors:

/lammps-29Oct20/src/fix_conp_dyn.cpp: In member function ‘virtual void LAMMPS_NS::FixConpDyn::post_integrate()’:
/lammps-29Oct20/src/fix_conp_dyn.cpp:116:117: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
             if (me == 0) fprintf(outf,"At step %d, couldn't increase or decrease check interval\n",update->ntimestep);
                                                                                                    ~~~~~~~~~~~~~~~~~^
/lammps-29Oct20/src/fix_conp_dyn.cpp:120:138: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
  if (me == 0) fprintf(outf,"At step %d, increasing explicit check interval to every %d steps\n",update->ntimestep,dyn_interval);
                                                                                                 ~~~~~~~~~~~~~~~~~             ^
/lammps-29Oct20/src/fix_conp_dyn.cpp:124:138: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
  if (me == 0) fprintf(outf,"At step %d, decreasing explicit check interval to every %d steps\n",update->ntimestep,dyn_interval);
                                                                                                 ~~~~~~~~~~~~~~~~~             ^
/lammps-29Oct20/src/fix_conp_dyn.cpp:127:121: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
             if (me == 0) fprintf(outf,"At step %d, initializing dynamic update, stage %d\n",update->ntimestep,dyn_status);
                                                                                             ~~~~~~~~~~~~~~~~~           ^
[ 25%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/fix_conp_dyn2.cpp.o
/lammps-29Oct20/src/fix_conp_dyn2.cpp: In member function ‘virtual void LAMMPS_NS::FixConpDyn2::b_cal()’:
/lammps-29Oct20/src/fix_conp_dyn2.cpp:137:113: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
           fprintf(outf,"%d\tbk\t%d\t%d\t%g\t%g\n",update->ntimestep,bk_interval,bk_interval_new,bk_err,bk_runerr);
                                                   ~~~~~~~~~~~~~~~~~                                             ^
/lammps-29Oct20/src/fix_conp_dyn2.cpp:179:113: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘LAMMPS_NS::bigint {aka long int}’ [-Wformat=]
           fprintf(outf,"%d\tbp\t%d\t%d\t%g\t%g\n",update->ntimestep,bp_interval,bp_interval_new,bp_err,bp_runerr);



....



[  6%] Built target compute.h
Consolidate compiler generated dependencies of target lammps
[  6%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/force.cpp.o
In file included from /lammps-29Oct20/build/styles/style_kspace.h:15:0,
                 from /lammps-29Oct20/src/force.cpp:19:
/lammps-29Oct20/src/pppm_conp_intel.h:28:10: fatal error: pppm_intel.h: No such file or directory
 #include "pppm_intel.h"
          ^~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/lammps.dir/build.make:2861: recipe for target 'CMakeFiles/lammps.dir/lammps-29Oct20/src/force.cpp.o' failed
make[2]: *** [CMakeFiles/lammps.dir/lammps-29Oct20/src/force.cpp.o] Error 1
CMakeFiles/Makefile2:681: recipe for target 'CMakeFiles/lammps.dir/all' failed
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by srtee** [comment]
Hi! The reason for the error is that some components of the constant potential code (ie pppm/conp/Intel) depend on the USER INTEL package but you have not installed it in your current build.

I will be updating the installation instructions to take that into account soon. For now you can just delete all "*intel*" files from the USER-CONP2 package and proceed.

Alternatively you can install USER INTEL (which is highly recommended, since it is a really good accelerator package) and keep going.

All the best!

**Comment by saffari101** [comment]
Hi Shern, Thanks a lot for the prompt reply and the help. Could you please let me know which one is the correct way to install USER-INTEL with cmake. Actually I could simply try them but would be great to make sure that from you as well :

**1.**  "cmake -D INTEL_ARCH=cpu -D INTEL_LRT_MODE=threads ../cmake"
_(from: https://docs.lammps.org/Build_extras.html#user-intel)_
or

**2.**  "cmake -D PKG_USER-INTEL=yes ../cmake"

Best Regards,

**Comment by saffari101** [comment]
Dear Shern!  thanks a lot for the prompt reply and help. I installed USER-INTEL and compilation proceeded further until 54% and ended with these different errors. Could you please help about them. I do really thank you for the help. Also looking forward for your update on installation instructions.


[ 52%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/potential_file_reader.cpp.o
[ 52%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp.cpp.o
[ 53%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = float; acc_t = double]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = double; acc_t = double]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = float; acc_t = float]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
CMakeFiles/lammps.dir/build.make:5101: recipe for target 'CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o' failed
make[2]: *** [CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o] Error 1
CMakeFiles/Makefile2:681: recipe for target 'CMakeFiles/lammps.dir/all' failed
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by saffari101** [comment]
Dear Shern! thanks a lot for your prompt reply and help. Installing USER-INTEL helped compilation proceed further but it ended at 64% with the following warnings and errors. Could you please take a look and guide me the reasons behind. Also looking forward for your updates on the installation instructions.


[ 64%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/potential_file_reader.cpp.o
[ 64%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp.cpp.o
[ 64%] Building CXX object CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = float; acc_t = double]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = double; acc_t = double]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
/lammps-29Oct20/src/pppm_conp_intel.cpp: In member function ‘void LAMMPS_NS::PPPMCONPIntel::ele_make_rho(LAMMPS_NS::IntelBuffers<flt_t, acc_t>*) [with flt_t = float; acc_t = float]’:
/lammps-29Oct20/src/pppm_conp_intel.cpp:532:24: error: ‘ele2tag’ not specified in enclosing ‘parallel’
       int i = atom->map(ele2tag[iele]);
               ~~~~~~~~~^~~~~~~~~~~~~~~
/lammps-29Oct20/src/pppm_conp_intel.cpp:506:11: error: enclosing ‘parallel’
   #pragma omp parallel LMP_DEFAULT_NONE \
           ^~~
CMakeFiles/lammps.dir/build.make:5101: recipe for target 'CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o' failed
make[2]: *** [CMakeFiles/lammps.dir/lammps-29Oct20/src/pppm_conp_intel.cpp.o] Error 1
CMakeFiles/Makefile2:681: recipe for target 'CMakeFiles/lammps.dir/all' failed
make[1]: *** [CMakeFiles/lammps.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by srtee** [comment]
Hi!

Could you update to the latest version of the code and see if it works? I have just made a small change that should fix that error.

**Comment by saffari101** [comment]
Hi Shern,

I tried with the latest version you updated, but the same error happened. Then, by removing the "_intel_" files from CONP2 and recompiling without INTEL-USER, it proceeded until 100%; however, in the very end I got these errors:

[100%] Linking CXX static library liblammps.a
[100%] Built target lammps
[100%] Building CXX object CMakeFiles/lmp.dir/lammps-29Oct20/src/main.cpp.o
[100%] Linking CXX executable lmp
liblammps.a(fix_conp.cpp.o): In function `LAMMPS_NS::FixConp::update_charge()':
/lammps-29Oct20/src/fix_conp.cpp:1078: undefined reference to `ddot_'
liblammps.a(fix_conp.cpp.o): In function `LAMMPS_NS::FixConp::inv()':
/lammps-29Oct20/src/fix_conp.cpp:907: undefined reference to `dgetrf_'
/lammps-29Oct20/src/fix_conp.cpp:909: undefined reference to `dgetri_'
liblammps.a(fix_conp.cpp.o): In function `LAMMPS_NS::FixConp::get_setq()':
/lammps-29Oct20/src/fix_conp.cpp:1043: undefined reference to `ddot_'
collect2: error: ld returned 1 exit status
CMakeFiles/lmp.dir/build.make:100: recipe for target 'lmp' failed
make[2]: *** [lmp] Error 1
CMakeFiles/Makefile2:1228: recipe for target 'CMakeFiles/lmp.dir/all' failed
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by srtee** [comment]
Hi,

This means the CMake compilation is failing to link MKL BLAS / LAPACK properly. This is unfortunately cropping up often enough that I may have to go with a more portable solution eventually. For now, can you try adding the flag `-D FFT=MKL` to your cmake command? 

And if that doesn't work, try the following flag instead:

`D CXX_FLAGS=-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_sequential -lmkl_core`

where ${MKLROOT} can be replaced with the place where MKL is installed.

**Comment by saffari101** [comment]
Hi,
I have tried both ways and also others based on your comments in other threads in USER-CONP2. For the (-D FFT=MKL), the same error. In the alternative flag in previous message the arguments were not recognized (CMake Error: Unknown argument -lmkl_core and also for -lmkl_intel_lp64 -lmkl_sequential).

 I tired this also the following based on your comments in other threads: (-D MKL_INCLUDE_DIR=/opt/intel/mkl/include -D MKL_LIBRARY=/opt/intel/mkl/lib/intel64 -D CMAKE_CXX_FLAGS='-lblas -llapack' -D CMAKE_CXX_FLAGS=-L${MKLROOT}/lib/intel64)

**Some part of the output for cmake ../cmake was :**
...
...
-- The following tools and libraries have been found and configured:
 * Git
 * MPI
 * OpenMP
 * PkgConfig
 * MKL

-- <<< Build configuration >>>
   Operating System: Linux
   Build type:
   Install path:     /root/.local
   Generator:        Unix Makefiles using /usr/bin/make
-- Enabled packages: KSPACE;MANYBODY;MOLECULE;RIGID
-- <<< Compilers and Flags: >>>
-- C++ Compiler:     /usr/bin/c++
      Type:          GNU
      Version:       7.5.0
      C++ Flags:    -L/lib/intel64
      Defines:       LAMMPS_SMALLBIG;LAMMPS_MEMALIGN=64;LAMMPS_OMP_COMPAT=3;LAMMPS_GZIP;LAMMPS_FFMPEG;FFT_MKL;FFT_MKL_THREADS
 
...

**and the output for compile was:**

Consolidate compiler generated dependencies of target lmp
[ 98%] Linking CXX executable lmp
/usr/bin/ld: cannot find /opt/intel/mkl/lib/intel64: File format not recognized
collect2: error: ld returned 1 exit status
CMakeFiles/lmp.dir/build.make:102: recipe for target 'lmp' failed
make[2]: *** [lmp] Error 1
CMakeFiles/Makefile2:1198: recipe for target 'CMakeFiles/lmp.dir/all' failed
make[1]: *** [CMakeFiles/lmp.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2




The error says (cannot find /opt/intel/mkl/lib/intel64: File format not recognized), while the path is right.  In opt/intel/mkl/lib there are two directories of intel64 and  intel64_lin

**Comment by srtee** [comment]
Hi,

I think we're almost there -- but the MKL_LIBRARY flag has to point to the actual library _file_ (with .so ending), not just the directory. Try this and see:

`-D MKL_LIBRARY=/opt/intel/mkl/lib/intel64/libmkl_rt.so`

**Comment by saffari101** [comment]
Dera Shern! 

Done! It worked. Thank you very much for your kind help. liblammps.a and executable lmp were generated properly. I do appreciate your helps.
