### ISSUE TITLE
USER-DRUDE package compatability

### ISSUE THREAD

**Issue by llangford1** [srtee/lammps-USER-CONP2#21]
Hi thanks for developing this code. I compiled it without the Intel related cpp and h files, and it works fine on some example inputs and a few other lammps calculations I had. However, when using this fix in conjunction with the USER-DRUDE package on lammps it starts to output segmentation faults. (The lammps calculation that throws segmentation faults when fix conp is used runs fine when the fix conp command is not used.) Is the fix conp command currently incompatible with the USER-DRUDE package?

**Comment by srtee** [comment]
Hi! I know that the previous version of the code written by Zhenxing Wang was compatible with USER-DRUDE, so there is no reason why the current code can't work with it -- but I have not actively tested for compatibility with USER-DRUDE in a while now so it's possible that I have written in a subtle bug or issue that causes problems. I am happy to take a look at where the problem might lie if you can send me a small test input to work with.

**Comment by srtee** [comment]
Off the top of my head, if you are hoping to add Drude electrons to the *electrode particles*, that definitely won't work (and shouldn't work because that would be representing the polarizability of the electrode in two different ways, through CPM and through Drude polarization, which overcounts the polarization response and shouldn't be physically appropriate).

**Comment by llangford1** [comment]
Sorry it was hasty for me to assume fix conp was the issue here. After running through gdb it looks like the problem was not actually with fix conp. Things are working fine now, thanks so much.

**Comment by srtee** [comment]
No problem! Thank you for your feedback. I hope you enjoy using the code, and do let me know if there are any further issues or if you foresee room for further collaboration.

all the best,
Shern
