### ISSUE TITLE
Help for new fix command

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#28]
Dear Dr. Shern,

I noticed that the fix conp has been modified to:

fix [ID] [group1] conp [Nevery] [group2] [η] [DV]
fix [ID] [group1] conq [Nevery] [group2] [η] [QR] 

Could you please let me how the newscript would be for:
fix e all conp 1 1.979 ${molleft} ${molright} -0.6 0.6 inv

Also how do we define the total charge QR in conq? for example what is an optimum or lets say typical value for an aqueous electrolyte and electrodes with -0.6V and 0. 6 V?

Can we skip the fix conq and not to set the QR as I don't know what is the typical value for my system?

Bests regards,

**Comment by srtee** [comment]
Hi,

This set of commands will do the same thing:

group eleleft molecule ${molleft}
group eleright molecule ${molright}
fix e eleleft conp 1 eleright 1.979 1.2

Fix conq is a completely separate and new command. Apologies, I should make that clear in my description.

All the best,
Shern

**Comment by saffari101** [comment]
I do appreciate for the prompt reply,

Best regards,
