### ISSUE TITLE
Does ffield is suitable for my system? 

### ISSUE THREAD

**Issue by saffari101** [srtee/lammps-USER-CONP2#33]
Hello dear, 

I am using your implemented code for my research. One of my systems is similar to the attached image which has electrolyte in the backside of the electrodes as well. I wanted to use ffiled, but I was wondering whether it would be correct or not,  since we impose an efiled in the direction of lets say from -z toward +z (if left electrode is charged negatively), and what would be the direction of electric field in electrolyte solution behind of the electrodes according to the image.  I do appreciate your help  

![Capture](https://user-images.githubusercontent.com/17302654/148061215-82f56907-cd0d-4098-b018-d9bbaa7884a5.JPG)

**Comment by srtee** [comment]
If your system is z-periodic then you are simulating an infinite array of negative and positive electrodes, one after the other, in the z-direction.

Assuming that is what you want, then you should use the "noslab" option to turn off slab corrections in CONP2. Finite field is for systems that are _meant_ to be non-periodic in z.

Hope that helps! As always please make sure that your simulation is physically reasonable and that you know how to verify the results you are getting.

**Comment by saffari101** [comment]
thank a lot for the help, I appreciate it.
