### ISSUE TITLE
Error in fix conp command while running the test code

### ISSUE THREAD

**Issue by AyshaSiddikaAsha** [srtee/lammps-USER-CONP2#37]
Hello,

I have built 27May2021 patch of LAMMPS . While running the input script from dilute (from tests folder), I faced the error:

ERROR: Fix conp group ID does not exist (src/USER-CONP2/fix_conp.cpp:107)
Last command: fix e all conp 1 1.979 ${molleft} ${molright} -0.5 0.5 inv iter etypes 1 3

But the molleft and molright variable is already defined in the input script. I am not understanding where the problem is then. Could anyone please help me about this? 

Thank you.

N.B: I have set n value as 1 and processor value as 1 in the input script.

**Comment by srtee** [comment]
Dear AyshaSiddikaAsha,

My apologies -- I changed the input syntax in the latest updates (it's a lot simpler, and uses groups instead of molecules) but hadn't changed the inputs in most of the test folders. I have updated those inputs now. Let me know if they're working now for you!

**Comment by AyshaSiddikaAsha** [comment]
Dear Shern Tee,

Thank you so much for your help. They are working perfectly now!
