### ISSUE TITLE
Using the compute potential/atom function

### ISSUE THREAD

**Issue by ms123456-TX** [srtee/lammps-USER-CONP2#39]
I want to use the compute potential/atom function, how can I get it?

**Comment by srtee** [comment]
The compute potential/atom function is already present in the latest version of the code. The following keywords are possible:

`pair` -- calculate only pair part of potential

`kspace` -- calculate only long range part of potential

`eta [eta] [molidL] [molidR]` -- apply Gaussian width to the charges in molecules with number molidL and molidR.

Note that _I cannot guarantee that these results are accurate_ (by comparison, the main CPM code has been used to produce results in the linked arXiv paper, which has just been accepted into JCP). So please have a plan for validating any results by other means (for example solving the Poisson equation on the charge density profile).

**Comment by ms123456-TX** [comment]
I am also trying to output voltage by solving Poisson equation, but I find that no matter how I divide the size of the bin, the sum of the charges of the whole system is not zero? Is it possible that the Poisson equation integral is no longer sufficient for the 3D CPM? Is there another way to do it?
