### ISSUE TITLE
Is the Finite field method equilibrium electric field accurate?

### ISSUE THREAD

**Issue by ms123456-TX** [srtee/lammps-USER-CONP2#41]
Is it accurate to apply a reverse electric field in the one-dimensional direction to balance the electric field generated in three dimensions?

**Comment by srtee** [comment]
In the finite field method, you should apply an electric field equal to minus the potential difference divided by the cell length in the intended direction (usually z).

When done this way, a finite field simulation should have the same short term evolution as a slab mode simulation (numerical drift means the simulations will eventually diverge as errors add up). See our recent paper: https://aip.scitation.org/doi/10.1063/5.0086986

**Comment by ms123456-TX** [comment]
Thank you for your patient answer! 
Is this method still applicable in complex electrodes (e.g. porous electrodes, MOFs, etc.)?

**Comment by srtee** [comment]
Hi there,

For discussing more about the scientific aspects of constant potential modelling (and not just tech help) feel free to email me at s.tee@uq.edu.au.
