### ISSUE TITLE
LAMMPS_NS::GridComm" has no member "reverse_comm_kspace

### ISSUE THREAD

**Issue by cron-weasley** [srtee/lammps-USER-CONP2#42]
I have a error, I want to know,your gcc version 、intel version、and lammps version。
../pppm_conp.cpp(114): error: class "LAMMPS_NS::GridComm" has no member "reverse_comm_kspace"
    gc->reverse_comm_kspace(dynamic_cast<KSpace*>(this),1,sizeof(FFT_SCALAR),REVERSE_RHO,
        ^

../pppm_conp.cpp(122): error: class "LAMMPS_NS::GridComm" has no member "forward_comm_kspace"
    gc->forward_comm_kspace(dynamic_cast<KSpace*>(this),1,sizeof(FFT_SCALAR),FORWARD_AD,

**Comment by cron-weasley** [comment]
my gcc version is gcc 11 ,intell 2020u4   lammps version is 2022

**Comment by srtee** [comment]
Hi, sorry for the late reply -- I was about to ask you for your LAMMPS version. I will probably set up a branch for the 2022 LAMMPS version which isn't supported by this version of code.

Note that the latest stable build of LAMMPS (23Jun2022) contains the ELECTRODE package which includes almost all of the capabilities of this package (plus a few others). If you want to try it, you can avoid a lot of pain of using custom code!

**Comment by cron-weasley** [comment]
thanks ! I have solved this problem。The reason is that the lambs version must be 27May2021, not any other version

**Comment by cron-weasley** [comment]
Dear Tee，
Thanks for your reply!
As you said after using your LAMMPS (23Jun2022) all works ok.
Thanks a lot!
________________________________
发件人: Shern Tee ***@***.***>
发送时间: 2022年7月18日 14:44
收件人: srtee/lammps-USER-CONP2 ***@***.***>
抄送: cron-weasley ***@***.***>; Author ***@***.***>
主题: Re: [srtee/lammps-USER-CONP2] LAMMPS_NS::GridComm" has no member "reverse_comm_kspace (Issue #42)


Hi, sorry for the late reply -- I was about to ask you for your LAMMPS version. I will probably set up a branch for the 2022 LAMMPS version which isn't supported by this version of code.

Note that the latest stable build of LAMMPS (23Jun2022) contains the ELECTRODE package which includes almost all of the capabilities of this package (plus a few others). If you want to try it, you can avoid a lot of pain of using custom code!

―
