### ISSUE TITLE
Using CPM in EMD or NEMD

### ISSUE THREAD

**Issue by ms123456-TX** [srtee/lammps-USER-CONP2#44]
Dear Professor,

I noticed that there may be a problem with this cpm method for NEMD? Does this problem require whether the electrodes are fixed or not?
 Is there also a problem with using it for EMD?
Or could I use this cpm code without fixed the electrodes?

I want to use this code for heat-related simulations and I sincerely ask for your help!

Thanks a lot!

**Comment by srtee** [comment]
Hi there,

Equilibrium results have previously been replicated between Ewald and PPPM successfully.

As described on the README page, the PPPM/conp solver in this package doesn't work correctly when I try to do Poiseuille flow (https://www.thermopedia.com/content/1042/) in between charged walls when using PPPM. Using an Ewald solver I obtain the expected result (the fluid between the walls speeds up and flows and some energy is dissipated via friction with the walls), but using the PPPM solver I don't (the fluid between the walls speeds up exponentially and the simulation crashes).

You can quickly verify this yourself simply by running simulations with either `ewald/conp` or `pppm/conp` as the `kspace` solver, and checking the results. If you see any behavior different from what I described above it is a bug and should be filed as an issue. It is possible that this behavior was related to Issue #40, and fixing that also fixed the pppm/conp NEMD bug (but I haven't tested it yet).

Note that the code as currently implemented assumes that the electrode particles are fixed. `fix electrode/conp` has no way of knowing if the electrode particles are moving over time, and it will continue updating charges as if the charged electrode particles were fixed at their original positions. This may be an acceptable approximation, or it may be completely wrong -- that is a scientific problem to be solved for your specific system, and I don't know the answers for my systems either.

If you are happy with fixed electrode particles and want to study NEMD, I would suggest you take a look at the ELECTRODE package. It is included with the latest stable version of LAMMPS (23 Jun 2022) and has very similar syntax to this package (https://docs.lammps.org/fix_electrode_conp.html). It gives the correct behavior for "Poiseuille flow" with rigid electrodes. (But rigid electrodes probably do not give the correct amount of wall drag -- it might still be close enough, or it might not.)

**Comment by ms123456-TX** [comment]
Dear Professor,

Thanks  for your patient answer!
If the electrode must be fixed, can we apply the potential to the outermost side in a flat plate electrode?(Because generally I set the potential is set in the innermost side of the electrode.)

Thanks!
Best regards!
